/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Principal;
export const Time = IDL.Int;
export const ChatSession = IDL.Record({
  'id' : SessionId,
  'title' : IDL.Text,
  'created' : Time,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'createSession' : IDL.Func([IDL.Text], [], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(ChatSession)], ['query']),
  'getAllSessionsByTitle' : IDL.Func([], [IDL.Vec(ChatSession)], ['query']),
  'getMessages' : IDL.Func([SessionId], [IDL.Vec(Message)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Principal;
  const Time = IDL.Int;
  const ChatSession = IDL.Record({
    'id' : SessionId,
    'title' : IDL.Text,
    'created' : Time,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'createSession' : IDL.Func([IDL.Text], [], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(ChatSession)], ['query']),
    'getAllSessionsByTitle' : IDL.Func([], [IDL.Vec(ChatSession)], ['query']),
    'getMessages' : IDL.Func([SessionId], [IDL.Vec(Message)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };